version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      DEBUG: 1
      WATCHFILES_FORCE_POLLING: true
    restart: on-failure
    working_dir: /app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  mongodb_container:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data_db:/data/db
